languageCode = "en"
languageName = "English"
weight = 1
title = "Taller de Git"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/blowfish_logo_transparent.png"
  logo = "img/git.png"
  # secondaryLogo = "PATH"
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Taller de Git"
  #image = "img/blowfish_logo.png"
  image = "img/git.png"
  headline = "Aprende lo básico para trabajar de manera individual o colaborativa."
  bio = "Aprende lo básico para trabajar de manera individual o colaborativa."
#  links = [
#    { twitter = "https://twitter.com/burufugu" },
#    { mastodon = "https://masto.ai/@blowfish" },
#    { github = "https://github.com/nunocoracao/blowfish" },
#  ]

  
